#!/bin/sh -e

set -x

mypy starlette_audit --ignore-missing-imports
autoflake --in-place --recursive --remove-unused-variables starlette_audit tests
black starlette_audit tests
isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply starlette_audit tests