#!/bin/sh -e

set -x

pytest --cov=starlette_audit --cov-report=xml
mypy starlette_audit --ignore-missing-imports
autoflake --recursive --remove-unused-variables starlette_audit tests
black starlette_audit tests --check
